    CREATE TABLE IF NOT EXISTS Jobs (
        jobkey VARCHAR(255) PRIMARY KEY,
        viewJobLink TEXT(2500),
        link TEXT(2500),
        normTitle VARCHAR(255),
        title VARCHAR(255),
        displayTitle VARCHAR(255),
        company VARCHAR(255),
        truncatedCompany VARCHAR(255),
        thirdPartyApplyUrl TEXT(2500),
        companyRating DECIMAL(3, 1),
        companyReviewCount INT,
        featuredEmployer BOOLEAN,
        featuredEmployerCandidate BOOLEAN,
        feedId INT,
        formattedActivityDate VARCHAR(50),
        formattedLocation VARCHAR(255),
        formattedRelativeTime VARCHAR(50),
        jobLocationState VARCHAR(2),
        jobLocationCity VARCHAR(255),
        extractedSalary_max DECIMAL(12, 2),
        extractedSalary_min DECIMAL(12, 2),
        extractedSalary_type VARCHAR(50),
        openInterviewsInterviewsOnTheSpot BOOLEAN,
        openInterviewsJob BOOLEAN,
        openInterviewsOffersOnTheSpot BOOLEAN,
        openInterviewsPhoneJob BOOLEAN,
        remoteLocation BOOLEAN,
        sourceId INT, -- Add this column
        createDate DATETIME DEFAULT CURRENT_TIMESTAMP,
        pubDate DATETIME DEFAULT CURRENT_TIMESTAMP,
        expired BOOLEAN DEFAULT 0
    )